export const Component = {
  RestApplication: Symbol.for('RestApplication'),
  Logger: Symbol.for('Logger'),
  Config: Symbol.for('Config'),
  DatabaseClient: Symbol.for('DatabaseClient'),
  UserService: Symbol.for('UserService'),
  UserModel: Symbol.for('UserModel'),
  OfferModel: Symbol.for('OfferModel'),
  OfferEntity: Symbol.for('OfferEntity'),
  OfferService: Symbol.for('OfferService'),
  CommentModel: Symbol.for('CommentModel'),
  CommentService: Symbol.for('CommentService'),
  FavoriteModel: Symbol.for('FavoriteModel'),
  FavoriteService: Symbol.for('FavoriteService'),
  OfferController: Symbol.for('OfferController'),
  AppExceptionFilter: Symbol.for('AppExceptionFilter'),
  UserController: Symbol.for('UserController'),
} as const;
